### ISSUE TITLE
c_cpp_properties.json doesn't have my own includePath and defines

### ISSUE THREAD

**Issue by eydonmlau** [politoleo/iar#10]
Hi,  The extension does automatically generate the c_cpp_properties, but in the  c proprieties config file ,it doesnot have my own includePath and defines, It just like this
```
"includePath": [
                "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.0\\arm\\inc\\c",
                "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.0\\arm\\inc"
            ],
```
So ,without my project includePath ,Compile Error like this:
```
Fatal Error[Pe1696]: cannot open source file "board.h"
...
```

What should I do now ?
Regards.

**Comment by politoleo** [comment]
Hi, you need to add the include path to the IAR Project: https://www.youtube.com/watch?v=bRRUkF0jMyc

**Comment by eydonmlau** [comment]
Thans for reply.
 In IAR , I do add the include path, and it is ok when compile it in iar
The IncludePath and defines like this:
![includepath](https://user-images.githubusercontent.com/19401578/42317050-fd9626bc-807d-11e8-9387-b1047ffaa8a0.png)

Regards

**Comment by eydonmlau** [comment]
Thanks for the Hints,
I use "config":"Debug"， instead of[ "Debug","Release"],  and it's ok now. 
why? because I saw there two configurations, including "Debug" and "Release", so I supposed I should write 2 configurations.
Besides, Can I rebuild the project?

**Comment by politoleo** [comment]
You could delete everything from the build folder and than press the shortcut to rebuild the whole project, since the standard behaviour is incremental build. 
Do not hesitate to write if you have some suggestions to make the extension better, thank you!
