### ISSUE TITLE
IarBuild.exe on IAR Workbench 7.0 doesn't support the -parallel flag

### ISSUE THREAD

**Issue by vgg15** [politoleo/iar#11]
Hi, 

I'm trying to run the  extension on VSCode with IAR workbench 7.0. 
I cannot build the project. It seems that this version does not accept the -parallel compile flag. 

Could you provide a fix for the 7.0 version?

Thanks

**Comment by politoleo** [comment]
Hi, starting from v1.5 you could disable parallel flag by adding "parallel" : false to iar.json config file
