### ISSUE TITLE
Why I cannot find iar.enable in the default settings?

### ISSUE THREAD

**Issue by JadenLiu0103** [politoleo/iar#13]
I already enable the plugin, and complete the iar.json in .vscode.

But I cannot find iar.enable in the default folder settings.

The vscode version I used is version 1.26.1 with x64 architecture.
![image](https://user-images.githubusercontent.com/31171249/44612637-8785d800-a83c-11e8-8d37-d713b9cc1f95.png)

**Comment by politoleo** [comment]
You could just write it even if it's not there

Da: JadenLiu0103
Inviato: sabato 25 agosto, 01:57
Oggetto: [politoleo/iar] Why I cannot find iar.enable in the default settings? (#13)
A: politoleo/iar
Cc: Subscribed


I already enable the plugin, and complete the iar.json in .vscode.
But I cannot find iar.enable in the default folder settings.
The vscode version I used is version 1.26.1 with x64 architecture.
