### ISSUE TITLE
Change of config is not used

### ISSUE THREAD

**Issue by sbomber** [politoleo/iar#18]
If I change the iar.json - config value, save the file, and issue IAR Build, the previous config value is used.  In order for the new value to be used I must restart VSCode.

**Comment by politoleo** [comment]
Thanks, I will fix this shortly!

**Comment by sbomber** [comment]
Cool.  I appreciate it!

**Comment by sbomber** [comment]
I tried a different method, which may help you when fixing this.  I wanted to see if 'Close Workspace' and then reopen the workspace would cause the change to be seen.  The answer is yes.

**Comment by politoleo** [comment]
Thanks, I plan to use the "file changed" signal to reload the configuration, I was aware of the bug but always forgot to fix it 👍

**Comment by politoleo** [comment]
Added with 1.5

**Comment by politoleo** [comment]
Added with 1.5
