### ISSUE TITLE
Debugadapterprocess ended with "read error"

### ISSUE THREAD

**Issue by gharti** [politoleo/iar#19]
Hello,

I'm trying to debug my STM32 project with this extension. Compiling works fine, but the debugging fails with a "read error". 

I just don't know where i can find some informations on this error. Is there any common place (like a log output) where i can find the reason for this read error?

Thanks a lot

**Comment by politoleo** [comment]
Debugging is done by the vscode-cpptools extension: https://github.com/Microsoft/vscode-cpptools
Anyway, this is something that works for me with J-Link:

> {
>   "version": "0.2.1",
>   "configurations": [
>     {
>       "name": "Debug J-Link",
>       "type": "cppdbg",
>       "request": "launch",
>       "program": "${workspaceRoot}/OUT.out",
>       "stopAtEntry": true,
>       "cwd": "${workspaceRoot}",
>       "externalConsole": false,
>       "MIMode": "gdb",
>       "miDebuggerPath": "C:\\GCC\\arm\\bin\\arm-none-eabi-gdb.exe",
>       "debugServerPath": "C:\\Program Files (x86)\\SEGGER\\JLink_V622d\\JLinkGDBServerCL.exe",
>       "debugServerArgs": "-if swd -singlerun -endian little -speed auto -port 3333 -device STM32F303VE -vd -halt",
>       "serverStarted": "Connected\\ to\\ target",
>       "serverLaunchTimeout": 5000,
>       "targetArchitecture": "arm",
>       "filterStderr": false,
>       "filterStdout": true,
>       "logging": {
>         "trace": false,
>         "traceResponse": false,
>         "engineLogging": false
>       },
>       "setupCommands": [
>         {
>           "text": "target remote localhost:3333"
>         },
>         {
>           "text": "monitor flash breakpoints = 1"
>         },
>         {
>           "text": "monitor flash download = 1"
>         },
>         {
>           "text": "monitor reset"
>         },
>         {
>           "text": "load C:/Users/Desktop/TEST/OUT.out"
>         },
>         {
>           "text": "monitor reset"
>         }
>       ]
>     }
>   ]
> }

**Comment by gharti** [comment]
Thanks for your very fast reply and sorry for my poor description. 

The error was not inside my program (which could be debugged with the vscode-cpptools), but instead vscode did not start the debugging process because of the mentioned "read error". 

Maybe one of my the specified paths in the launch.json is wrong, i thought. So I'm looking for a way to check the startup process of the debugger and the jlink server (i.e. watch/verify the used parameters)

My launch configuration is here (it looks very similar to yours)
      {
        "name": "Debug J-Link",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceRoot}\\out.out",
        "stopAtEntry": true,
        "cwd": "${workspaceRoot}",
        "externalConsole": false,
        "MIMode": "gdb",
        "miDebuggerPath": "C:\\Program Files (x86)\\GNU Tools Arm Embedded\\7 2018-q2-update\\bin\\arm-none-eabi-gdb.exe",
        "debugServerPath": "C:\\Program Files (x86)\\SEGGER\\JLink_V640\\JLinkGDBServerCL.exe",
        "debugServerArgs": "-if swd -singlerun -endian little -speed auto -port 3333 -device STM32F207VE -vd -strict -halt",
        "serverStarted": "Connected\\ to\\ target",
        "serverLaunchTimeout": 5000,
        "filterStderr": false,
        "filterStdout": true,
        "setupCommands": [
          {"text": "target remote localhost:3333"},
          {"text": "monitor flash breakpoints = 1"},
          {"text": "monitor flash download = 1"},
          {"text": "monitor reset"},
          {"text": "load C:/03_src/out.out"},
          {"text": "monitor reset"}
        ]
      }
