### ISSUE TITLE
iar.json

### ISSUE THREAD

**Issue by Pillasaar** [politoleo/iar#2]
Hello,

I can't find an iar.json file in .vscode folder? Do I just create one and add just these three lines in there?
{
    "iar.enabled":true
}

What about the bit in 'configuration' sections?
I have the launch.json file. Can I use this extension with E2 lite as well?

Regards,

**Comment by politoleo** [comment]
Hi, yes you should create a iar.json file in .vscode folder with a code that should look like this:

```
{
    "version": 1,
    "path": "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.0\\",
    "project": "${workspaceRoot}\\project\\MyProject.ewp",
    "config": "Debug",
}
```

replace:
> "path": "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.0\\",

with your IAR installation folder

> ${workspaceRoot}\\project\\MyProject.ewp

 with your project location,

> "config": "Debug",

with your project configuration (those are listed in IAR editor in the combo box located on "Workspace" pane)

Than you need to add the following line

> "iar.enabled":true

on vscode workspace settings: File->Preferences->Setting->Workspace Settings.


This extension has nothing to do with launch.json nor with the debug, it will just compile your code and do all setting for you, the debugger part is provided by ms-vscode.cpptools extension.

You should be able to use your debugger with vscode if the debugger provides a GDB server and you have a cross-compiled GDB debugger for your target.

**Comment by Pillasaar** [comment]
Hello,

I think I understand it better now. So I opened the default settings in VS code, expanded 'IAR Configuration', clicked on the edit icon and set iar.enabled to true.

I then did a cntrl+shift+b and it says 'No IAR configuration file found'. What am I doing wrong?

Regards,
Sudhi

**Comment by Pillasaar** [comment]
Hi,

Sorry, didn't see your reply there, think we posted the same time.
And yes this is what I did just before my last reply. So it says  'No IAR configuration file found' when I do cntrl+shift+b.
I am using reneas Rx63 processor and E2 lite emulator. Not sure it provides a GDB server.

Regards,
Sudhi
