### ISSUE TITLE
What is the advantages of this extension ?

### ISSUE THREAD

**Issue by Eldadc** [politoleo/iar#22]

**Comment by politoleo** [comment]
Advantages relative to IAR Editor?
It let you navigate your IAR code much faster, with proper feature like a modern IDE, while IAR Workbench is slow and sometime it doesn't work at all (navigate trough code or autocompletation)
Without extension you would need to edit the "c_cpp_properties.json" file manually, wich is a nightmare to do.
It also let you compile and debug it, but that's a side feature.

**Comment by Eldadc** [comment]
Thanks on the quick answer. I will give it a try.
Is there a git plugin for IAR IDE ? What is the best practice when working git and IAR IDE.

Thanks

**Comment by politoleo** [comment]
I believe there is an official support for git already built in in IAR.
I use vscode also for git management, I found it very easy and fast. Plus I could run also other kind of code belonging to the same firmware project, like unit test, HIL and simulations!
