### ISSUE TITLE
settings.json problem

### ISSUE THREAD

**Issue by gitmek** [politoleo/iar#24]
I'm trying to get the plugin to work, but I am stuck at settings.json

![image](https://user-images.githubusercontent.com/50925799/58198581-d038c780-7cce-11e9-8e30-142acd050697.png)

It has been working before, but it did not update the paths in MS intellisense json file, so i decided to start over again. - Deleted all .vscode folders, opend my source folder, saved the workspace added iar.json and settings.json and now nothing works. :-(  ... Compare with picture
Any help appreciated. 
regards GM

**Comment by politoleo** [comment]
Hi, ”iar.enabled” : true should be in the user or workspace “settings.json”, could you try?

Da: gitmek <notifications@github.com>
Inviato: mercoledì 22 maggio 2019 20:23
A: politoleo/iar <iar@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: [politoleo/iar] settings.json problem (#24)


I'm trying to get the plugin to work, but I am stuck at settings.json

[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F50925799%2F58198581-d038c780-7cce-11e9-8e30-142acd050697.png&data=02%7C01%7C%7Cc16d0f31a34245331b4b08d6dee290ce%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636941461997909998&sdata=pt4NS1ct%2B7C4uWs2ioBEqn6TWXMVIc%2Bdmd%2BmyM4AMos%3D&reserved=0>

It has been working before, but it did not update the paths in MS intellisense json file, so i decided to start over again. - Deleted all .vscode folders, opend my source folder, saved the workspace added iar.json and settings.json and now nothing works. :-( ... Compare with picture
Any help appreciated.
regards GM

**Comment by gitmek** [comment]
Hi,
I did so still i got this problem...
![image](https://user-images.githubusercontent.com/50925799/58201008-5f94a980-7cd4-11e9-9850-3fa15d5f2992.png)

**Comment by gitmek** [comment]
I also tried this:
![image](https://user-images.githubusercontent.com/50925799/58201357-30326c80-7cd5-11e9-9403-223c10d4474e.png)
there are no errors in the workspace config file as you can see but c_cpp_properties.json do not get updated

**Comment by politoleo** [comment]
Could you try the same but without using workspace?

Da: gitmek <notifications@github.com>
Inviato: mercoledì 22 maggio 2019 20:59
A: politoleo/iar <iar@noreply.github.com>
Cc: Leonardo <politoleo@hotmail.it>; Comment <comment@noreply.github.com>
Oggetto: Re: [politoleo/iar] settings.json problem (#24)


Hi,
I did so still i got this problem...
[image]<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F50925799%2F58201008-5f94a980-7cd4-11e9-9850-3fa15d5f2992.png&data=02%7C01%7C%7C6b6d6248a34f4693d62608d6dee78894%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636941483336043872&sdata=c0Dx9T1NeMKp3PZDqFR13xGHAjaMf6HHhrM8NYicMIY%3D&reserved=0>

**Comment by gitmek** [comment]
Good Morning! :-)
I made a complete new IAR project with all files in one hierarchic folder structure. 
I opened the top folder in VS Code without saving a workspace.
Then edited settings.json and iar.json. - They seem to have no prob. Building with shift+ctrl+b works

But still no c_cpp_properties.json is generated.  :'(

**Comment by politoleo** [comment]
Could you upload the whole folder somewhere so I could have a look?
Thank you
________________________________

**Comment by gitmek** [comment]
... Thanks...
Had to create an empty c_cpp_properties.json and rebuild the setting with shift ctrl b.
voila c_cpp_properties.json got filled up...

next step will be: Testing it with workspace again... :-D

Thanks for your support 👍

**Comment by gitmek** [comment]
Hi again!
I do not get it to run in a workspace... 
The settings files is buildt, but the c_cpp_properties.json will not get updated.

1. I opened the root folder of my project
2. Opend a source file, so that .vscode will be created
3. Saved the Workspace into the root folder
4. Added iar.json
5. Enabeld in the Extension settings workspace: iar: Enabled
6. Buildt the code-worspace file
7. No c_cpp_properties.json got created
8. Clicked on a lightbulb of a header file, so that c_cpp_properties.json is created
9. re-build the code-workspace file
10. c_cpp_properties.json is unaltered, nothing added.

I am out of ideas...

![image](https://user-images.githubusercontent.com/50925799/58309709-3f183c80-7e05-11e9-8423-6d033207c9a8.png)

SecondProject.code-workspace:
`{`
	`"folders": [`
		`{`
			`"path": "."`
		`}`
	`],`
	`"settings": {`
		`"iar.enabled": true`
	`}`
`}`

iar.json:
`{`
 `   "version": 1,`
  `  "path": "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.0\\",`
   ` "project": "C:\\Data\\SecondProject\\EWARM\\SecondProject.ewp",`
    `"config": "SecondProject",`
    `"parallel" : true`
`}`

**Comment by gitmek** [comment]
Update:
The workaround of sbomber [(https://github.com/politoleo/iar/issues/18)](https://github.com/politoleo/iar/issues/18), also applied for this problem. - c_cpp_properties.json will now get updated...

> I tried a different method, which may help you when fixing this. I wanted to see if 'Close Workspace' and then reopen the workspace would cause the change to be seen. The answer is yes.

**Comment by politoleo** [comment]
Good I really think it's an appropriate moment to fix this issue!
Thank you
________________________________

**Comment by politoleo** [comment]
Fixed with 1.5
