### ISSUE TITLE
Auto add user create source file to IAR's ewp and ewt

### ISSUE THREAD

**Issue by JiZhiqi** [politoleo/iar#27]
This is a good extension,but when I use it,I found when I create a new c source file,CTRL+SHIFT+B get make error.after my research,I found the file isn't add in IAR's ewp and ewt file, so can it auto add the user new source file to the both file(ewp and ewt)?ths~ ^_^

**Comment by politoleo** [comment]
I could have 10 source file in the folders but only compile 2 of them, becouse IAR use a project structure instead of a folder structure, so I don't think it would be a good idea.
