### ISSUE TITLE
I am unable to build using visual studio code

### ISSUE THREAD

**Issue by jay28panchal** [politoleo/iar#4]
Can you please explain me step by step how to use visual studio code for build the IAR code. 
I already installed your extension but now I don't understand what to do please help me.

**Comment by politoleo** [comment]
Hi, did you follow the instruction?

You need to create a file named "iar.json" inside your ".vscode" folder, like this:
```
{
    "version": 1,
    "path": "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench\\",
    "project": "C:\\Projects\\TEST\\TEST.ewp",
    "config": "Debug"
}
```

Then you con into your workspace settings, and enable the extension, that is disabled by default:
```
{
    "iar.enabled":true
}
```
Then just run ctrl+shift+b to start build.

**Comment by jay28panchal** [comment]
I have created iar.jason file as below inside .vscode folder as you
suggested like this

{
"version": 1,
"path": "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.0",
"project": "C:\\JAY\\DEEP_ZSTACK_SWMOD_CORD\\Z-Stack Mesh 1.0.0\\Projects\\
zstack\\SW_MOD _MACtoNWK_01-02-18\\Switch Module 5.1\\CC2530DB\\
GenericApp.ewp",
"config": "Debug"
}

but I dont know where to create file like below.....

{
    "iar.enabled":true
}



Regards,

-*Jay Panchal*
Embedded Developer
Mo.*+919662278074*
Email
*jay28panchal@gmail.com <jay28panchal@gmail.com>*

**Comment by politoleo** [comment]
Hi, it needs to be into your workspace setting:
https://code.visualstudio.com/docs/getstarted/settings
