### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by aenima1891** [politoleo/iar#8]
I've installed the extension,  but if I run ctrl+shift+b, build doesn't start.
![immagine](https://user-images.githubusercontent.com/1100887/37835499-9a29939e-2eb0-11e8-8685-d33bc5103e0b.png)

This is my iar.json in my .vscode folder
`{
	"version": 1,
	"path": "C:/Program Files (x86)/IAR Systems/Embedded Workbench 7.0/",
	"project": "${workspaceRoot}/project.ewp",
	"config": "Debug_GC"
}
`

and these are my workspace settings
`{
	// estensione IAR abilitata
	"iar.enabled": true
}`

**Comment by politoleo** [comment]
Could you try to restart vscode?

**Comment by aenima1891** [comment]
@politoleo Thanks for the reply
I've restarted VSCode twice without any success

**Comment by politoleo** [comment]
That's odd..
That error should only happens in 2 conditions:

1) Extension is not installed or enabled:

![image](https://user-images.githubusercontent.com/6762551/37839855-d684f576-2ebb-11e8-91ac-606cc858ba01.png)

2) iar.enabled is not in the right place:

![image](https://user-images.githubusercontent.com/6762551/37839952-1c5b09a0-2ebc-11e8-9ab9-53a8e5f7bd20.png)


Could you please check both?

**Comment by politoleo** [comment]
Could you also please try to hit "F1", and then in the command palette start to write "IAR", you should see the command:

![image](https://user-images.githubusercontent.com/6762551/37840305-fc46b1b8-2ebc-11e8-8365-20fc0c9129c6.png)

Does it appears?

**Comment by aenima1891** [comment]
I see the command IAR: Build Project.
If I run it, vscode start the build, but it's "freezed" in this state 
![immagine](https://user-images.githubusercontent.com/1100887/37842204-c64a769e-2ec1-11e8-8b62-387cd7ba97c1.png)

**Comment by aenima1891** [comment]
I've written a simple task.json file for build IAR project inside vscode
`{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Debug - Rebuild All",
			"type": "shell",
			"command": "\"C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 7.0\\common\\bin\\IarBuild.exe\" ${workspaceRoot}\\project.ewp -build Debug_GC -log info | sed.exe -e 's/\\[/ /' -e 's/\\]//' -e 's/Error/error/'  -e 's/Warning/warning/",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher": [
				"$msCompile"
			]
		},
		{
			"label": "Debug - Build",
			"type": "shell",
			"command": "\"C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 7.0\\common\\bin\\IarBuild.exe\" ${workspaceRoot}\\project.ewp -make Debug_GC -log info | sed.exe -e 's/\\[/ /' -e 's/\\]//' -e 's/Error/error/'  -e 's/Warning/warning/",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher": [
				"$msCompile"
			]
		},
		{
			"label": "Debug - Clean",
			"type": "shell",
			"command": "\"C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 7.0\\common\\bin\\IarBuild.exe\" ${workspaceRoot}\\project.ewp -clean Debug_GC -log info | sed.exe -e 's/\\[/ /' -e 's/\\]//' -e 's/Error/error/'  -e 's/Warning/warning/",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher": [
				"$msCompile"
			]
		}
	]
}`

It simply calls IarBuild.exe for every configuration and it modify the build output with sed.exe to permit the vscode error console to detect errors/warnings/infos correctly.

However, I'd prefear to use your solution which is more integrated and allows debug on chip.

**Comment by politoleo** [comment]
What version of Iar are you using exactly? I tested it with all version starting from 7.4.

The extension actually does call IarBuild.exe but there may be some problem with parsed output.
