### ISSUE TITLE
`c_cpp_properties.json` doesn't update.

### ISSUE THREAD

**Issue by g-berthiaume** [politoleo/iar#9]
In your package description, there's mention of the update of the c proprieties config file:

> The extension automatically replaces your c_cpp_properties.json Microsoft C++ Tools configuration to matches the IAR Project ones. It supports browsing to external files, includepath, common defines and user included one.

I'm not exactly sure what you mean by "automatically", but when i build my project with `ctrl+shift+b`, everything build correctly, but my `c_cpp_properties.json` is not updated.
Updating the c_cpp file would be incredible to facilitate the use of the nice feature of vscode.

```
Additional information:

OS: Win10 x64
Vscode: 1.24.1
IAR Workbench: 8.22.2
```
Thanks for your time.

**Comment by politoleo** [comment]
Hi, yes it should be automatically generated so you could navigate the code.
Could you try to restart vscode and delete c_cpp_properties.json if any?

You should see it automatically generated with all includepath and defines.
Thanks!

**Comment by g-berthiaume** [comment]
After the following tests, the file is still not generated. 😢 

### Test bench

0. Deleted the `c_cpp_properties.json` file.
1. Reload vscode and build (`ctrl+shift+b`) project with the extension.
2. Disable and re-enable the extension (`politoleo.iar`) and build (`ctrl+shift+b`) project with the extension.
3. Restart vscode and build (`ctrl+shift+b`) project with the extension.
4. Restart computer and build (`ctrl+shift+b`) project with the extension.

### Additional information:

- This is the project file tree:
![tree](https://user-images.githubusercontent.com/19377511/41487104-44e2137e-70b5-11e8-9b02-bff562d8d408.PNG)

- This is the feedback i get after building:
![cmd_out](https://user-images.githubusercontent.com/19377511/41487082-2a42d576-70b5-11e8-8c93-706456e4612d.PNG)

- Your extension and vscode is up to date. 
- I have the `ms-vscode.cpptools` extension installed.

- My `iar.json` file is as follows:
```json
{
    "version": 1,
    "path": "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.0\\",
    "project": "C:\\Users\\GBerthiaume\\projets\\1. THERMO\\code\\1 - Controller\\Firmware\\trunk\\Code Source\\Controller\\EWARM\\Controller.ewp",
    "config": "Controller"
}
```
- The workspace setting (`settings.json`) is as follow:
```json
{
    "iar.enabled": true
}
```

Maybe there's an action that i didn't do ? 
Thanks for your quick answer. If you have any question, do not hesitate to contact me.

**Comment by g-berthiaume** [comment]
I think got it. 😄 

While I'm still not able to generate the  `cpp_properties.json` file in this project, **i was able to generate it** in an other project.

I have an hypothesis on why it did work this time:

The first time i used your extension, my `iar.json` was not configured properly : the "config" parameter was wrong. Is it possible that if you build  (`ctrl+shift+b`) the project with a wrong ` iar.json`, it wont be able to generate the `cpp_properties.json` file, even if you correct the ` iar.json` afterward?

As my javascript skills are somewhat limited, I won't be able to help you directly with a pull request, but feel free to contact me.

Thanks for your extension and have a great day.

**Comment by politoleo** [comment]
I'm so sorry I missed the previous comment, somehow the mail didn't show up!

I think It may have something to do with project path.
Would you mind to move the project that is not working in a simple path, i.e. short and with no spaces, points and special characters?

Thank you!

**Comment by g-berthiaume** [comment]
I just came out of vacation. I will do the test ASAP.
Have a good day.

**Comment by g-berthiaume** [comment]
It was indeed the file path. 👍 
I changed the project directory to `C:\\Users\\GBerthiaume\\Controller\\EWARM\\Controller.ewp`  and it worked.
The `c_cpp_properties.json` was correctly generated.

Thank you for your support. 
You can consider this issue has closed.

**Comment by politoleo** [comment]
Thank you for your feedback, I'm happy you are able to use it!
I will try with different path to understand where is the bug.

**Comment by markdubo** [comment]
Hi. I have the same problem. `c_cpp_properties.json` is not being generated or updated. My path has no spaces and I have moved it to a shorter path: 
`{
    "version": 1,
    "path": "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 6.0\\",
    "project": "C:\\scratch\\MainCode\\Project\\IAR\\NIBP_OEM_main.ewp",
    "config": "Debug",
    "parallel" : false
}`
The project builds fine.
Have you any idea what the issue is?
Thanks
